<?php
$this->layout()->headerTitle = $product->title;
$this->inlinescript()->appendFile( $this->basePath('js/wds/mobile/imageswitcher.js') )
?>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">商品信息</li>
    <li>
        <div class="product-images imageswitcher">
            <table>
                <tr>
                    <td class="image-col">
                        <div class="full-image-wrapper">
                            <img alt="" src="<?=$product->product_images[0]->uri?>">
                        </div>
                    </td>
                    <td class="thumbnails-col">
                        <?php foreach ($product->product_images as $key => $image):?>
                        <?php if ($key == 0) :?>
                        <div><img alt="" src="<?=$image->thumbnail_uri?>" data-fullimage="<?=$image->uri?>" class="thumb-active"></div>
                        <?php else :?>
                        <div><img alt="" src="<?=$image->thumbnail_uri?>" data-fullimage="<?=$image->uri?>"></div>
                        <?php endif;?>
                        <?php endforeach;?>
                    </td>
                </tr>
            </table>
        </div>
        <div class="product-info">
            <span><?=$product->title?></span>
            <span><?=$product->category->title?></span>
            <div>¥ <?=$product->price?> / <?=$product->unit?></div>
        </div>
    </li>
    <li data-role="list-divider">详细说明</li>
    <li><?=$product->short_desc?></li>
</ul>