<?php $headerTitle = '首页';?>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">商品信息</li>
    <li>
        <div class="product-images">
            <table>
                <tr>
                    <td class="image-col">
                        <div class="full-image-wrapper">
                            <img alt="" src="<?=$product->product_images[0]->uri?>">
                        </div>
                    </td>
                    <td class="thumbnails-col">
                        <?php foreach ($product->product_images as $image):?>
                        <div><img alt="" src="<?=$image->thumbnail_uri?>"></div>
                        <?php endforeach;?>
                    </td>
                </tr>
            </table>
        </div>
        <div class="product-info">
            <span><?=$product->name?></span>
            <span><?=$product->category->name?></span>
            <div>¥ 9.90/5 件</div>
        </div>
    </li>
    <li data-role="list-divider">详细说明</li>
    <li><?=$product->short_desc?></li>
</ul>