<?php

$this->layout()->headerTitle = $product->title;
echo $this->partial('mobile/layout/breadcrumbs', array( 'category' => $category));
$this->inlinescript()->appendFile( $this->basePath('js/wds/mobile/imageswitcher.js') );
?>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">商品信息</li>
    <li>
        <div class="product-images imageswitcher">
            <?php if (!empty($product->product_images)):?>
            <table>
                <tr>
                    <td class="image-col">
                        <div class="full-image-wrapper">
                            <img alt="" src="<?=$product->product_images[0]->uri?>">
                        </div>
                    </td>
                    <td class="thumbnails-col">
                        <?php foreach ($product->product_images as $key => $image):?>
                        <?php if ($key == 0) :?>
                        <div><img alt="" src="<?=$image->thumbnail_uri?>" data-fullimage="<?=$image->uri?>" class="thumb-active"></div>
                        <?php else :?>
                        <div><img alt="" src="<?=$image->thumbnail_uri?>" data-fullimage="<?=$image->uri?>"></div>
                        <?php endif;?>
                        <?php endforeach;?>
                    </td>
                </tr>
            </table>
            <?php endif;?>
        </div>
        <div class="product-info">
            <p class="ui-li-desc"><?=$product->title?></p>
            <p><?=$category->title?></p>
            <p>¥ <?=$product->price?> / <?=$product->unit?></p>
        </div>
    </li>
    <li data-role="list-divider">详细说明</li>
    <li><?=$product->description?></li>
</ul>