<div class="sidebar responsive" id="sidebar">
    <script type="text/javascript">
        try {
            ace.settings.check('sidebar', 'fixed')
        } catch(e) {}
    </script>
    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
    	<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
    		<button class="btn btn-success">
    			<i class="ace-icon fa fa-signal"></i>
    		</button>

    		<button class="btn btn-info">
    			<i class="ace-icon fa fa-pencil"></i>
    		</button>

    		<!-- #section:basics/sidebar.layout.shortcuts -->
    		<button class="btn btn-warning">
    			<i class="ace-icon fa fa-users"></i>
    		</button>

    		<button class="btn btn-danger">
    			<i class="ace-icon fa fa-cogs"></i>
    		</button>

    		<!-- /section:basics/sidebar.layout.shortcuts -->
    	</div>

    	<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
    		<span class="btn btn-success"></span>

    		<span class="btn btn-info"></span>

    		<span class="btn btn-warning"></span>

    		<span class="btn btn-danger"></span>
    	</div>
    </div><!-- /.sidebar-shortcuts -->
    <!-- #sidebar-shortcuts -->
    <ul class="nav nav-list">
        <li class="active">
            <a href="index.html">
                <i class="icon-dashboard"></i>
                <span class="menu-text">
                    Dashboard
                </span>
            </a>
            <b class="arrow"></b>
        </li>
        <li>
            <a href="/project">
                <i class="icon-youtube-sign"></i>
                <span class="menu-text">
                    Project
                </span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="icon-youtube-sign"></i>
                <span class="menu-text">
                    CronJob
                </span>
            </a>
        </li>

        <li>
            <a href="calendar.html">
                <i class="icon-calendar"></i>
                <span class="menu-text">
                    Calendar
                    <span class="badge badge-transparent tooltip-error" title="2&nbsp;Important&nbsp;Events">
                        <i class="icon-warning-sign red bigger-130">
                        </i>
                    </span>
                </span>
            </a>
        </li>
    </ul>
    <!-- /.nav-list -->

	<!-- #section:basics/sidebar.layout.minimize -->
	<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
		<i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
	</div>

	<!-- /section:basics/sidebar.layout.minimize -->
	<script type="text/javascript">
		try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
	</script>
</div>
<!-- End .sidebar -->