<div class="sidebar responsive" id="sidebar">
    <script type="text/javascript">
        try {
            ace.settings.check('sidebar', 'fixed')
        } catch(e) {}
    </script>
    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
    	<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
    	</div>
    	<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
    	</div>
    </div><!-- /.sidebar-shortcuts -->
    <!-- #sidebar-shortcuts -->
    <ul class="nav nav-list">
        <li class="active">
            <a href="/admin/category">
                <i class="icon-dashboard"></i>
                <span class="menu-text">
                    分类管理
                </span>
            </a>
            <b class="arrow"></b>
        </li>
        <li>
            <a href="/admin/product">
                <i class="icon-youtube-sign"></i>
                <span class="menu-text">
                    产品管理
                </span>
            </a>
        </li>
    </ul>
    <!-- /.nav-list -->

	<!-- #section:basics/sidebar.layout.minimize -->
	<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
		<i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
	</div>

	<!-- /section:basics/sidebar.layout.minimize -->
	<script type="text/javascript">
		try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
	</script>
</div>
<!-- End .sidebar -->