<?php $headerTitle = '首页';?>
<ul data-role="listview" data-inset="true" class="ui-nodisc-icon ui-alt-icon">
	<li>优惠信息</li>
	<li><a href="#">更多优惠</a></li>
</ul>

<ul data-role="listview" data-inset="true" class="ui-nodisc-icon ui-alt-icon">
	<?php foreach ($categories as $category): ?>
	<li><a href="/mobile/category/id/<?=$category->id?>" data-transition="fade"><?= $category->name?></a></li>
	<?php endforeach;?>
</ul>