 <?php

 $title = 'Projects';
 $this->headTitle($title);
 ?>
 <div class="page-header">
    <h1>
        <?php echo $this->escapeHtml($title); ?>
        <small><a href="<?php echo $this->url('home/default', array('controller'=>'project', 'action'=>'add'));?>">Add new project</a></small>
    </h1>
 </div>

<div class="col-xs-12">
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Artist</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($projects as $project) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($project->name);?></td>
                <td><?php echo $this->escapeHtml($project->description);?></td>
                <td>
                    <a href="<?php echo $this->basePath('project/edit/id/' . $project->id);?>">Edit</a>
                    <a href="<?php echo $this->basePath('project/delete/id/' . $project->id);?>">Edit</a>
                 </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</div>
