<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
		<?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>


		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/css/font-awesome.min.css" />

		<!-- page specific plugin styles -->

		<!-- text fonts -->
		<link rel="stylesheet" href="/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="/css/ace.min.css" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="/css/ace-part2.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="/css/ace-skins.min.css" />
		<link rel="stylesheet" href="/css/ace-rtl.min.css" />

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->
		<script src="/js/ace-extra.min.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lte IE 8]>
		<script src="/js/html5shiv.js"></script>
		<script src="/js/respond.min.js"></script>
		<![endif]-->
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    </head>
    <body class="no-skin">
		<?=$this->partial('/layout/nav.phtml')?>
        <div class="main-container" id="main-container">
        	<script type="text/javascript">
        		try{ace.settings.check('main-container' , 'fixed')}catch(e){}
        	</script>

        	<?=$this->partial('/layout/sidebar.phtml')?>


        	<div class="main-content">
                <?=$this->partial('/layout/breadcrumbs.phtml')?>
                <div class="page-content">
        		  <?php echo $this->content; ?>
                </div>
        	</div>

        	<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        		<i class="icon-double-angle-up icon-only bigger-110"></i>
        	</a>
        </div><!-- /.main-container -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>
