<!-- <div data-role="footer" data-position="fixed"> -->
<!--     <div data-role="navbar"> -->
<!--     	<ul> -->
<!--     		<li><a href="#" data-rel="back" class="ui-btn ui-icon-back ui-btn-icon-left">Back</a></li> -->
<!--     		<li><a href="/" data-transition="fade" class="ui-btn ui-icon-home ui-btn-icon-left">主页</a></li> -->
<!--     		<li><a href="#" class="ui-btn-active ui-state-persist">类别</a></li> -->
<!--     		<li><a href="#">其他</a></li> -->
<!--     	</ul> -->
<!--     </div> -->
</div><!-- /footer -->