<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8" />
		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="/css/jquery.mobile-1.4.3.min.css" />
    	<script src="/js/jquery.min.js"></script>
    	<script src="/js/jquery.mobile-1.4.3.min.js"></script>
    	<style type="text/css">
    		.noshadow * {
    			-webkit-box-shadow: none !important;
    			-moz-box-shadow: none !important;
    			box-shadow: none !important;
    		}
    		form.ui-mini .ui-field-contain fieldset.ui-controlgroup legend small {
    			color: #666;
    		}
    		/* Page and overlay */
    		.ui-overlay-a,
    		.ui-page-theme-a,
    		.ui-page-theme-a .ui-panel-wrapper {
    			background-color: #f1f2e8 /*{a-page-background-color}*/;
    		}
    	</style>
        <?php echo $this->headTitle( $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    </head>
    <body>
    	<div data-role="page" id="testpage" class="ui-page-theme-a noshadow">
    		<div data-role="header">
    			<h1><?//=$headerTitle?></h1>
    		</div><!-- /header -->
    		<div class="ui-content" role="main">
    		    <?=$this->partial('/layout/breadcrumbs.phtml')?>
    			<?php echo $this->content; ?>
    		</div><!-- /content -->

    		<div data-role="footer" data-position="fixed">
		      <?=$this->partial('/layout/nav.phtml')?>
    		</div><!-- /footer -->

    	</div>

        <?php echo $this->inlineScript() ?>


    </body>
</html>
