<?php
$title = '商品管理';
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/wds/admin/category-list.js'));
?>
<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/admin/product/product/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12 flash-messager-container">
        <?=$this->flashMessenger()->render();?>

    </div>
</div>
<table id="category-table" class="table table-striped table-bordered table-hover">
    <thead>
    	<tr>
            <th>类别名称</th>
            <th>&nbsp;</th>
    	</tr>
    </thead>
</table>

<!-- Modal -->
<div class="modal" id="qrcodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-sm">
    <div class="modal-content">
      <div class="modal-body">
        <div class='qrcode-in-model'></div>
      </div>
    </div>
  </div>
</div>
