<?php
$title = 'Add new project';
$this->headTitle($title);
?>
<?= $this->pageHeader( $title )?>
<?php

$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('category_id'));
echo $this->formRow($form->get('short_desc'));
echo $this->formActions( $form->get('cancel'), $form->get('submit'));
echo $this->form()->closeTag();
?>
