 <?php

 $title = '商品管理';
 $this->headTitle($title);
 ?>
 <div class="page-header">
    <h1>
        <?= $this->escapeHtml($title); ?>
        <small><a href="<?= $this->url('home/default', array('controller'=>'product', 'action'=>'add'));?>"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
    </h1>
 </div>

<div class="col-xs-12">
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>商品名称</th>
                <th>商品类别</th>
                <th>说明</th>
                <th>图片</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
            <tr>
                <td><?= $this->escapeHtml($product->name);?></td>
                <td><?= $this->escapeHtml($product->category->name);?></td>
                <td><?= $this->escapeHtml($product->short_desc);?></td>
                <td></td>
                <td align="right">
                    <a href="<?= $this->basePath('product/edit/id/' . $project->id);?>">
                        <i class="ace-icon glyphicon glyphicon-pencil"></i>Edit
                    </a>
                    <a href="<?= $this->basePath('product/delete/id/' . $project->id);?>">
                        <i class="ace-icon glyphicon glyphicon-remove"></i>Delete
                    </a>
                 </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</div>
