 <?php
 $title = '商品管理';
 $this->headTitle($title);
 ?>
 <div class="page-header">
    <h1>
        <?= $this->escapeHtml($title); ?>
        <small><a href="/product/product/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
    </h1>
 </div>

<div class="col-xs-12">
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
<!--                 <td></td> -->
                <th></th>
                <th>商品名称</th>
                <th>商品类别</th>
                <th>价格</th>
                <th>单位</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
            <tr>
<!--                 <td><input type="checkbox"></td> -->
                <td><img alt="" src="<?=$product->productThumbnail?>"></td>
                <td><?= $this->escapeHtml($product->name);?></td>
                <td><?= $this->escapeHtml($product->category->name);?></td>
                <td><?= $this->escapeHtml($product->price);?></td>
                <td><?= $this->escapeHtml($product->unit);?></td>
                <td align="right">
                    <a href="<?= $this->basePath('product/product/edit/' . $product->id);?>">
                        <i class="ace-icon glyphicon glyphicon-pencil"></i>Edit
                    </a>
                    <a href="<?= $this->basePath('product/delete/id/' . $product->id);?>">
                        <i class="ace-icon glyphicon glyphicon-remove"></i>Delete
                    </a>
                 </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</div>
