<?php
$title = '商品管理';
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/wds/admin/product-list.js'));
?>
<style>
<!--
.qrcode-in-model{
	width: 130px;
	margin: auto;
}
.dataTables_wrapper .dataTables_processing {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 100%;
  height: 40px;
  margin-left: -50%;
  margin-top: -25px;
  padding-top: 20px;
  text-align: center;
  font-size: 1.2em;
  background-color: white;
}
-->
</style>
<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/admin/product/product/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12 flash-messager-container">
        <?=$this->flashMessenger()->render();?>

    </div>
</div>
<table id="product-table" class="table table-striped table-bordered table-hover">
    <thead>
    	<tr>
            <th class="hidden-480">&nbsp;</th>
            <th>商品名称</th>
            <th class="hidden-480">商品类别</th>
            <th>售价</th>
            <th class="hidden-480">推荐</th>
            <th>&nbsp;</th>
    	</tr>
    </thead>
</table>

<!-- Modal -->
<div class="modal" id="qrcodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-sm">
    <div class="modal-content">
      <div class="modal-body">
        打开微信“扫一扫”，打开网页后点击屏幕右上角分享按钮
        <div class='qrcode-in-model'></div>
      </div>
    </div>
  </div>
</div>
