<?php
$title = '商品管理';
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/wds/admin/product-list.js') )
?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/product/product/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12 flash-messager-container">
        <?=$this->flashMessenger()->render();?>
        <table class="table table-striped table-bordered table-hover table-condensed">
            <thead>
                <tr>
    <!--                 <td></td> -->
                    <th>&nbsp;</th>
                    <th>商品名称</th>
                    <th>商品类别</th>
                    <th>价格</th>
                    <th>单位</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($products as $product) : ?>
                <tr data-id="<?=$product->id?>">
    <!--                 <td><input type="checkbox"></td> -->
                    <td><img alt="" src="<?=$product->productThumbnail?>"></td>
                    <td><?= $this->escapeHtml($product->title);?></td>
                    <td><?= $this->escapeHtml($product->category->title);?></td>
                    <td><?= $this->escapeHtml($product->price);?></td>
                    <td><?= $this->escapeHtml($product->unit);?></td>
                    <td align="right">
                        <?php if ($product->recommend):?>
                        <a data-target="/product/product/recommend" data-method="ajax/get" data-recommend="0" >
                            <i class="ace-icon glyphicon glyphicon-pencil"></i>取消推荐
                        </a>
                        <?php else:?>
                        <a data-target="/product/product/recommend" data-method="ajax/get" data-recommend="1" >
                            <i class="ace-icon glyphicon glyphicon-pencil"></i>推荐到首页
                        </a>
                        <?php endif;?>
                        <a href="<?= $this->basePath('product/product/edit/' . $product->id);?>">
                            <i class="ace-icon glyphicon glyphicon-pencil"></i>编辑
                        </a>
                        <a href="<?= $this->basePath('product/delete/id/' . $product->id);?>">
                            <i class="ace-icon glyphicon glyphicon-remove"></i>删除
                        </a>
                     </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>